server.port: 9999
server.contextPath: /api
solon.app:
  name: 'top.primsnet'
  group: 'prims'
solon.env: dev
#配置后台管理mysql数据库
db.db1:
  type: "com.zaxxer.hikari.HikariDataSource"
  default: "db_rock0"
  strict: true
  db_rock0:
    driverClassName: org.sqlite.JDBC
    jdbcUrl: jdbc:sqlite:./src/main/resources/db/datapulse.db
#redis配置
redis.cache1:
  driverType: "redis" #驱动类型
#  keyHeader: "demo" #默认为 ${solon.app.name} ，可不配置
  defSeconds: 30 #默认为 30，可不配置
  server: "127.0.0.1:6379"
  db: 0 #默认为 0，可不配置
  password: "123456"
  idleConnectionTimeout: 10000
  connectTimeout: 10000
#配置rabbitmq
solon.cloud.rabbitmq:
  server: 127.0.0.1:5672   #rabbitmq 服务地址
  username: admin           #rabbitmq 链接账号
  password: admin
  event:
    publishTimeout: 3000
    virtualHost: "test"
#配置es
test.esx:
  url: 127.0.0.1:9200
  username: elastic
  password: elastic

#配置mybatis-plus
mybatis.db1:
  typeAliases:    #支持包名 或 类名 //支持 ** 和 *
    - "top.primsnet.sync.business.**.vo"
  mappers:        #支持包名 或 类名 或 xml（.xml结尾）//支持 ** 和 *
#    - "classpath:mapper/*.xml"
    - "top.primsnet.sync.business.**.mapper"
  configuration:
    cacheEnabled: false
    mapperVerifyEnabled: false
    mapUnderscoreToCamelCase: true
#    logImpl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  globalConfig:
    banner: false
    metaObjectHandler: "top.primsnet.sync.config.mp.MetaObjectHandlerImpl"
    dbConfig:
      logicDeleteField: "deleted"
      logicDeleteValue: "2"
#分页组件的配置
pagehelper:
  banner: false
  offsetAsPageNum: true
  rowBoundsWithCount: true
  pageSizeZero: true
  reasonable: false
  params: pageNum=pageHelperStart;pageSize=pageHelperRows;
  supportMethodsArguments: false

--- ### 接口文档配置
springdoc:
  def-package: top.primsnet.sync.business
  # 设置对象型参数的展示形式（设为 true 表示将对象型参数平展开，即对象内的属性直接作为参数展示而不是嵌套在对象内，默认 false）
  # 如果不添加该全局配置，可以在需要如此处理的对象参数类上使用 @ParameterObject
  default-flat-param-object: true
#引入其他配置文件
solon:
  config:
    load:
      - app-data-push.yml
#日志打印机别控制
solon.logging.appender:
  console:
    level: INFO
  file:
    name: "logs/${solon.app.name}"